config/routes.rb
PatientFilteringSystem::Application.routes.draw do
  resources :trials do
    resources :exams
  end

 resources :patients do
  member do
    get 'take_exam'
    post 'finalize_exam'
  end
 end

  root :to => 'trials#index'

end

app/models/exam.rb
class Exam < ActiveRecord::Base
  attr_accessible :question, :answers, :type, :trial_id
  belongs_to :trial
  has_many :patient_answers

  set_inheritance_column :ruby_type

  def qtype
    types = {
      1 => "Fixed Answer",
      2 => "Short Answer",
      3 => "Multiple Choice"
    }

    types[type.to_i]
  end

end

app/models/patient.rb
class Patient < ActiveRecord::Base
  attr_accessible :fname, :mname, :lname, :email, :dob, :father_name, :mobile, :phone, :city, :country, :state, :trial_id

  belongs_to :trial
  has_many :exams
  has_many :patient_answers

  def full_name
    "#{fname} #{mname} #{lname}"
  end

  def address
    "#{city} #{state} #{country}"
  end

  def result
    result = {}
    exam_ids = trial.exams.map(&:id)
    patient_answers.where('exam_id in (?)', exam_ids).map do |p_answer|
     exam = p_answer.exam
     question = exam.question
     answer = exam.answers
     my_answer = p_answer.answer
     remark = p_answer.remark
     result.merge!({question => [answer, my_answer, remark]})
   end
   result
 end
end

app/models/patient_answer.rb
class PatientAnswer < ActiveRecord::Base
  attr_accessible :answer, :patient_id, :exam_id, :status
  belongs_to :exam
  belongs_to :patient

  def remark
    statuses = {
      0 => "Wrong",
      1 => "Right",
    }

    statuses[status.to_i]
  end
end

app/models/test.rb
class Test < ActiveRecord::Base
  attr_accessible :question, :answers, :type, :trial_id
  belongs_to :trial

  set_inheritance_column :ruby_type

  def qtype
    types = {
      1 => "Fixed Answer",
      2 => "Short Answer",
      3 => "Multiple Choice"
    }

    types[type.to_i]
  end

end

app/models/trial.rb
class Trial < ActiveRecord::Base
  attr_accessible :name, :description
  has_many :vacancies
  has_many :exams
  has_many :patients
end

app/models/vacancy.rb
class Vacancy < ActiveRecord::Base
  attr_accessible :trial_period, :max_subject, :closing_date
  belongs_to :trial
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/exams_controller.rb
class ExamsController < ApplicationController

  def index
    @trial = Trial.find params['trial_id']
    @exams = Exam.where(trial_id: @trial.id)
  end

  def new
    @trial = Trial.find params['trial_id']
    @exam = @trial.exams.new
  end


  def create
    trial = Trial.find params['trial_id']
    @exam = trial.exams.new(params['exam'])
    respond_to do |format|
      if @exam.save
        format.html { redirect_to trial_exams_path(trial.id) , notice: "Exam added successfully."}
      else
        format.html { render action: "new" }
      end
    end
  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController

  def index
    @patients = Patient.where(trial_id: params['trial_id'])
  end

  def new
    @trials = Trial.all
    if @trials.present?
      @patient = Patient.new
    else
      render :text => "Sorry, no trials available. Try latter."
    end
  end

  def create
    @trial = Trial.find params['trial']
    @patient = @trial.patients.new(params['patient'])
    respond_to do |format|
      if @patient.save
        session['exams'] = [0]
        format.html { redirect_to take_exam_patient_path(@patient.id, { trial_id: @trial.id }) , notice: "Patient added successfully."}
      else
        format.html { render action: "new" }
      end
    end
  end

  def take_exam
    @patient = Patient.find params["id"]
    @trial = Trial.find params["trial_id"]
    @exam = @trial.exams.where('id not in (?)', session['exams']).last
    @progress = ((session['exams'].count-1)/@trial.exams.count.to_f)*100
  end

  def finalize_exam
    exam = Exam.find params['id']
    answer = params['answer']
    status = answer.downcase == exam.answers.downcase ? 1 : 0
    exam.patient_answers.create(answer: answer, status: status, patient_id: params['patient_id'])
    session['exams'] << params['id'].to_i
    is_more = exam.trial.exams.where('id not in (?)', session['exams']).present?

    if is_more
      redirect_to take_exam_patient_path(params['patient_id'], {trial_id: exam.trial_id})
    else
      session['exams'] = [0]
      render :text => "The exam is over. Thank you."
    end
  end

end

app/controllers/tests_controller.rb
class TestsController < ApplicationController

  def index
    @trial = Trial.find params['trial_id']
    @tests = Test.where(trial_id: @trial.id)
  end

  def new
    @trial = Trial.find params['trial_id']
    @test = @trial.tests.new
  end


  def create
    trial = Trial.find params['trial_id']
    @test = trial.tests.new(params['test'])
    respond_to do |format|
      if @test.save
        format.html { redirect_to trial_tests_path(trial.id) , notice: "Test added successfully."}
      else
        format.html { render action: "new" }
      end
    end
  end
end

app/controllers/trials_controller.rb
  class TrialsController < ApplicationController

  def index
    @trials = Trial.limit(50)
  end

  def new
    @trial = Trial.new
  end

  def create
    @trial = Trial.new(params['trial'])
    respond_to do |format|
      if @trial.save
        format.html { redirect_to trials_path , notice: "Trail #{@trial.name} added successfully."}
      else
        format.html { render action: "new" }
      end
    end
  end

  def destroy
    @trial = Trial.find params['id']
    redirect_to trials_path , notice: "Trail #{@trial.name} removed successfully." if @trial.destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/exams/_form.html.erb
<%= form_for [:trial, @exam], :html => { :class => 'form-horizontal' } do |f| %>
<div class="control-group">
  <%= f.label :question, :class => 'control-label' %>
  <div class="controls">
    <%= f.text_field :question, :class => 'text_field' %>
  </div>
</div>
<br />
<div class="control-group">
  <%= f.label :type, :class => 'control-label' %>
  <div class="controls">
    <%= f.select :type, options_for_select([['Fixed Answer', 1],['Short Answer',2],['Multiple Choice', 3]]), :class =>'qt_select' %>
  </div>
</div>
<br />
<div class="control-group">
  <%= f.label :answers, :class => 'control-label' %>
  <div class="controls answers">
    <%= f.text_field :answers, :class => 'text_field' %>
  </div>
</div>
<br />
<div class="form-actions">
  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
  trial_exams_path(@trial.id), :class => 'btn' %>
</div>
<% end %>



<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script type="text/javascript">
$("#exam_type").change( function() {
  var selected = $(this).val();
  var html = '' ;
  if(selected == 2){
    html = '<textarea class="text_field" id="exam_answers" name="exam[answers]" size="30" type="text_area">'
  }else if(selected == 3){
   html = '<input type="radio" name="exam[answers]" value="yes"> Yes<br>'+
   '<input type="radio" name="exam[answers]" value="not_sure"> Not Sure<br>'+
   '<input type="radio" name="exam[answers]" value="no"> No'
 }else{
  html = '<input class="text_field" id="exam_answers" name="exam[answers]" size="30" type="text">'
}
$('.answers').html(html);
});
</script>

app/views/exams/index.html.erb
<div class='header'>
  <div class="title"> Listing All Exams For The Trial </div>
</div>

<%= link_to 'Add +', new_trial_exam_path(@trial.id), :class => 'btn btn-primary pull-right' %>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Qestion</th>
      <th>Answer</th>
      <th>type</th>
    </tr>
  </thead>
  <tbody>
    <% @exams.each do |exam| %>
      <tr>
        <td><%= exam.question %></td>
        <td><%= exam.answers %></td>
        <td><%= exam.qtype %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<!-- <div class =".modal hide" id="view_modal_box" ></div>

<script>
 ($("a[data-toggle=modal]")).click(function() {
    var target, url;
    target = ($(this)).attr('data-target');
    url = ($(this)).attr('href');
    return ($(target)).load(url);
  });
</script> -->

app/views/exams/new.html.erb
<div class='header'>
  <div class="title"> Add Exam For The Trial</div>
</div>
<%= render :partial => 'form' %>

app/views/layouts/_flash_messages.html.erb
<%- flash.each do |name, msg| -%>
  <% if !msg.blank? %>

    <div class="wi_flash" id="flash_msg_hold">
      <span id="wi_flash_<%=name%>"> <%= msg %> </span>
    </div>

    <%= content_tag :script, :type => "text/javascript" do -%>
      $("#flash_msg_hold").animate({top:60},400 );
      $(".wi_flash").fadeOut(5000);
    <% end %>

  <% end %>
<%- end -%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PatientFilteringSystem</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navbar top-bar">
    <div class="navbar-inner">
      <a class="brand" href="#">Patient Filtering System</a>
      <ul class="nav nav-tabs pull-right">
        <li>
          <%= link_to "Patient", new_patient_path %>
        </li>
        <li class="active">
          <%= link_to "Admin", trials_path %>
        </li>
      </ul>
    </div>
  </div>

 <%= render :partial => "layouts/flash_messages" %>

  <%= yield %>

</body>
</html>

app/views/patients/_form.html.erb
<%= form_for @patient, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <label class="control-label"> Select trial to apply:</label>
    <div class="controls">
      <%= select_tag "trial", options_from_collection_for_select(@trials, "id", "name") %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :first_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :fname, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :middle_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :mname, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :last_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :lname, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :email, :class => 'control-label' %>
    <div class="controls">
      <%= f.email_field :email, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :father_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :father_name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :date_of_birth, :class => 'control-label' %>
    <div class="controls">
      <%= f.date_select :dob, :start_year => 1900, :end_year => Date.today.year, :class => 'date_select' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label 'Phone(mobile)', :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :mobile, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label 'Phone(landline)', :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :phone, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :city, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :city, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :state, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :state, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :country, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :country, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit 'Let me in', :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                patients_path, :class => 'btn' %>
  </div>
<% end %>

app/views/patients/index.html.erb
<div class='header'>
  <div class="title"> Listing All Patients Applied For The Trial</div>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Address</th>
      <th>Phone</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @patients.each do |patient| %>
      <tr>
        <td><%= patient.full_name %></td>
        <td><%= patient.email %></td>
        <td><%= patient.address %></td>
        <td><%= patient.phone %></td>
        <td><%= link_to 'View Exam', '#', :class => 'view_result' %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<!-- Light box for patient answer comparision -->

<div style="display:none">
  <div class='comparision'>
    <table class="table table-bordered">
      <thead>
        <tr>
          <th>Question</th>
          <th>Expected Answer</th>
          <th>Patient Answer</th>
          <th>Remark</th>
        </tr>
      </thead>
      <tbody>
        <% Patient.last.result.each_pair do |key, value| %>
        <tr>
          <td><%= key %></td>
          <td><%= value[0] %></td>
          <td><%= value[1] %></td>
          <td><%= value[2] %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<script>

$('.view_result').click(function(){
    $.fancybox($(".comparision").html(),{
    'transitionIn'  : 'elastic',
    'transitionOut' : 'elastic',
    'speedIn'     : 400,
    'speedOut'    : 200,
    'overlayShow' : true
  });
})
</script>

app/views/patients/new.html.erb
<div class='header'>
  <div class="title"> Enter Your Basic Information </div>
</div>
<%= render :partial => 'form' %>

app/views/patients/take_exam.html.erb
<div class='header'>
  <div class="title"> Answer The Following Question: </div>
</div>
<div class='examination'>
  <%= form_tag finalize_exam_patient_path(@exam.id, {patient_id: @patient.id}), :method => :post, :class => "form-inline" do %>

  <%= label_tag @exam.question, nil, :class => 'small_label' %>
  <%= text_field_tag 'answer' %>
  <%= submit_tag(value = "next") %>

  <% end %>
</div>
<div class="progress progress-striped active">
  <div class="bar" style="width: 0%;"></div>
</div>

<script>
var progress = <%= @progress %>;
console.log(progress);
$('.bar').css('width', progress+'%');
</script>

app/views/trials/_form.html.erb
<%= form_for @trial, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :description, :class => 'text_area', :rows => 3 %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit 'Add', :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                trials_path, :class => 'btn' %>
  </div>
<% end %>

app/views/trials/index.html.erb
<div class='header'>
  <div class="title"> Listing All Available Trials </div>
</div>

<%= link_to 'Add +', new_trial_path, :class => 'btn btn-primary pull-right' %>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @trials.each do |trial| %>
    <tr>
      <td><%= trial.name.humanize %></td>
      <td><%= trial.description %></td>
      <td>
        <%= link_to 'Exams', trial_exams_path(trial.id) %>
        <%= link_to 'Patients', patients_path({trial_id: trial.id }) %>
        <%#= link_to 'vacancies', '#' %>
        <%= link_to 'Delete', trial_path(trial),
        :method => :delete,
        :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) } %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/trials/new.html.erb
<div class='header'>
  <div class="title"> Add New Trial </div>
</div>
<%= render :partial => 'form' %>